/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#f8a010",
        "secondary": "#6bff8f",
        "on-tertiary-container": "#4a2c00",
        "primary-fixed": "#9396ff",
        "on-secondary-container": "#e4ffe2",
        "on-tertiary-fixed-variant": "#563400",
        "tertiary": "#ffb148",
        "on-primary-container": "#0a0081",
        "on-background": "#dee5ff",
        "inverse-primary": "#494bd7",
        "surface-dim": "#060e20",
        "secondary-container": "#006e2f",
        "secondary-dim": "#5bf083",
        "on-tertiary": "#573500",
        "primary-container": "#9396ff",
        "on-secondary": "#005f28",
        "surface-variant": "#192540",
        "error-container": "#a70138",
        "secondary-fixed-dim": "#5bf083",
        "surface-tint": "#a3a6ff",
        "inverse-surface": "#faf8ff",
        "surface": "#060e20",
        "tertiary-dim": "#e79400",
        "on-tertiary-fixed": "#2a1700",
        "outline-variant": "#40485d",
        "on-secondary-fixed-variant": "#006a2d",
        "inverse-on-surface": "#4d556b",
        "primary": "#a3a6ff",
        "on-error-container": "#ffb2b9",
        "surface-container-highest": "#192540",
        "tertiary-fixed-dim": "#e79400",
        "on-surface": "#dee5ff",
        "surface-container": "#0f1930",
        "on-secondary-fixed": "#004a1d",
        "primary-fixed-dim": "#8387ff",
        "on-error": "#490013",
        "secondary-fixed": "#6bff8f",
        "on-surface-variant": "#a3aac4",
        "surface-container-lowest": "#000000",
        "primary-dim": "#6063ee",
        "on-primary": "#0f00a4",
        "surface-bright": "#1f2b49",
        "background": "#060e20",
        "error-dim": "#d73357",
        "on-primary-fixed": "#000000",
        "tertiary-fixed": "#f8a010",
        "on-primary-fixed-variant": "#0e009d",
        "error": "#ff6e84",
        "surface-container-high": "#141f38",
        "outline": "#6d758c",
        "surface-container-low": "#091328"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
